######################################################################
# Automatically generated by qmake (2.01a) Mon Sep 22 10:46:42 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += douban_types.h doubanfm.h utils.hpp
FORMS += doubanfmdialog.ui
SOURCES += doubanfm.cpp main.cpp
QT += network phonon
LIBS += -lqjson
CONFIG += debug
RESOURCES += imgs.qrc
